name: ⚡️ Continuous Releases

on:
  push:
    branches:
      - main
      - 1.x
  merge_group:
  pull_request:

jobs:
  cr:
    name: "⚡️ Continuous Releases"

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build start
        run: pnpm run packages:build

      - name: Release
        run: |
          echo $(cat package.json | jq '.exports = .publishConfig.exports') > package.json
          pnpm dlx pkg-pr-new@0.0 publish './packages/start' --template './examples/*' --compact
